### ISSUE TITLE
DataFrame.from_html to read HTML tables

### ISSUE THREAD

**Issue by v0dro** [SciRuby/daru#219]
Having a `DataFrame.from_html` method would be great for reading HTML tables into dataframes directly from URLs.

**Comment by athityakumar** [comment]
@v0dro : Scraping gems like `mechanize` / `Nokogiri` can be used to get the data from html, but those html files can have any type of structure of tags where tables and data are located right? How can we get the exact data from html files - do we assume a a particular structure of the html files?

**Comment by zverok** [comment]
As for me:

1. It seems like nokoigiri should be enough
2. Daru should not depend on Nokogiri (as it is large binary gem, not always easy to install). So it should probably be a part of separate "daru importers" effort, as discussed in mailing list.
3. I believe investigation and clarification of requirements is a natural part of this tickets, so the order of proceeding should probably be the following:
  * gather some (different, yet real) examples of table data on the web
  * propose & discuss some method and options to handle decent amount of them
  * then, implement.

**Comment by athityakumar** [comment]
@zverok - I understood the part of using Nokogiri functionality and keeping Daru dependent on Nokogiri. However, the real issue is that - even if Nokogiri is used, we won't be able to get a proper desired output. Web scraping is done through specific searches for proper nodes that are parsed by Nokogiri from classes / divs that are actually present on the html file. And, for each website, this `searching through the nodes to get the desired data` approach willl be different and there is no automated / one single approach to get data in a reliable way, as opposed to extracting data from csv / json files.

**Comment by zverok** [comment]
Well, that's why I am saying about **gather some (different, yet real) examples of table data on the web** above. I assume (maybe wrongly) that this thing _could_ be imagined:

```ruby
Daru.from_html('https://en.wikipedia.org/wiki/Chiang_Mai', '.wikitable.collapsible:first')
```
(it is a [climate table](https://en.wikipedia.org/wiki/Chiang_Mai) on Chiang Mai page) could produce some reasonable output. Just by:
* skipping table headers;
* considering all `<th>`s as a parts of indexes (columns/rows);
* considering all `<td>`s as data.

Here is my prototype code to do so (not the best code in my life, ok; and it ignores td/th thing, just takes first col/cell as an indexes):
```ruby
require 'open-uri'
require 'nokogiri'
require 'daru'

doc = Nokogiri::HTML(open('https://en.wikipedia.org/wiki/Chiang_Mai'))
rows = doc.at('table.wikitable.collapsible').search('tr').map { |tr| tr.search('th,td').to_a }
maxcols = rows.map(&:count).max
rows.reject!{|r| r.count < maxcols }
colnames = rows.first.map(&:text)[1..-1]
rownames = rows[1..-1].map{|r| r.first.text }
data = rows[1..-1].map { |r| r[1..-1].map{|c|c.text.gsub("\n", ' ')} }
df = Daru::DataFrame.rows(data, index: rownames, order: colnames)
# #<Daru::DataFrame(10x13)>
#                    Jan        Feb        Mar        Apr        May        Jun        Jul        Aug        Sep        Oct        Nov        Dec       Year
#  Record hig 35.2 (95.4 37.7 (99.9 40.9 (105. 41.4 (106. 42.4 (108. 39.3 (102. 39.0 (102. 36.5 (97.7 35.8 (96.4 37.9 (100. 34.7 (94.5 33.4 (92.1 42.4 (108.
#  Average hi 29.8 (85.6 32.7 (90.9 35.2 (95.4 36.5 (97.7 34.2 (93.6 32.7 (90.9 31.8 (89.2 31.5 (88.7 31.7 (89.1 31.4 (88.5 30.1 (86.2 28.6 (83.5  32.2 (90)
#  Daily mean 21.5 (70.7  23.9 (75) 27.1 (80.8 29.3 (84.7 28.2 (82.8 27.6 (81.7  27.2 (81) 26.8 (80.2 26.7 (80.1  26.1 (79) 24.0 (75.2 21.4 (70.5 25.8 (78.4
#  Average lo 14.9 (58.8 16.2 (61.2 19.5 (67.1 22.9 (73.2 23.8 (74.8 24.0 (75.2  23.9 (75) 23.7 (74.7 23.2 (73.8  22.2 (72) 19.2 (66.6 15.7 (60.3 20.8 (69.4
#  Record low 8.6 (47.5) 9.4 (48.9) 13.0 (55.4 16.3 (61.3 18.3 (64.9 21.2 (70.2 20.5 (68.9 21.2 (70.2 19.5 (67.1 14.0 (57.2 9.3 (48.7) 3.8 (38.8) 3.8 (38.8)
#  Average ra 4.2 (0.165 8.9 (0.35) 17.8 (0.70 57.3 (2.25 162.0 (6.3 124.5 (4.9 140.2 (5.5 216.9 (8.5 211.4 (8.3 117.6 (4.6 53.9 (2.12 15.9 (0.62 1,130.6 (4
#  Average ra        0.7        0.9        2.3        6.8       15.0       17.1       18.9       20.9       17.8       11.7        4.9        1.4      118.4
#  Average re         68         58         52         57         71         77         79         81         81         79         75         73         71
#  Mean month      272.8      257.1      294.5      279.0      198.4      156.0      120.9      117.8      144.0      201.5      216.0      254.2    2,512.2
#  Mean daily        8.8        9.1        9.5        9.3        6.4        5.2        3.9        3.8        4.8        6.5        7.2        8.2        6.9
```
It seems to be generalizable.

**Comment by v0dro** [comment]
Here are some leads: http://pandas.pydata.org/pandas-docs/version/0.19.2/generated/pandas.read_html.html

Notice the gotchas.

**Comment by v0dro** [comment]
Try to make our HTML importer as robust or better than the pandas one. As @zverok says, it would be beneficial to first go over some examples of HTML tables.

**Comment by athityakumar** [comment]
Hmm - I went through the [html importer code](https://github.com/pandas-dev/pandas/blob/v0.19.2/pandas/io/html.py) of `pandas` and found that they are simply parsing and finding `<table>` , `<th>` and `<td>` tags for importing list of tables, with an option to search for a table with particular query strings.

Though this wouldn't be as reliable as traversing through nodes of html `div class` / `div id` elements, this is certainly a good start. :+1:

So, I think some think something like this should be possible -

```
dataframes = Daru.from_html('https://en.wikipedia.org/wiki/Chiang_Mai')[0]
=>   {
    B:['B8', 'B9', 'B10', 'B11'],
    F:['F8', 'F9', 'F10', 'F11'],
    D:['D8', 'D9', 'D10', 'D11']
  },
  index: [10,11,12,13]
```


And the Ruby equivalents for the web-scraping related libraries mentioned in the gotchas are `Nokogiri` & `Mechanize`. Infact, `Mechanize` itself is built on `Nokogiri`, but `Mechanize` is much more intuitive to code (That's just opinion after 6-months of web scraping with Ruby).

Also, a limiting case that I can visualize with the `from_html` function is - some websites store data in their `json` files, and call them through `inline js` inside their html files. In such cases, it's not possible to get data by web-scraping the `html` file - as it's the `json` file which is important.

**Comment by zverok** [comment]
What you are writing, is mostly correct, except probably for this:

> Infact, Mechanize itself is built on Nokogiri, but Mechanize is much more intuitive to code.

Yes, Mechanize is "simplifying" wrapper around Nokogiri, yet it adds unnecessary level of abstraction, while being less flexible than Nokogiri. So, I'd really advice you to get familiar with Nokogiri. And, in any case, remember that we can't make Nokogiri (or Mechanize) a strict dependency for Daru.

**Comment by athityakumar** [comment]
> So, I'd really advice you to get familiar with Nokogiri.

Actually, I learnt `Nokogiri` even before learning `Mechanize` as I didn't know during my initial days that `Mechanize` gem even existed. But ever since I found a gem of a gem (pun intended :wink:) called `Mechanize`, I've been working with only `Mechanize`- but yeah, it's always better to work with the basics.

> And, in any case, remember that we can't make Nokogiri (or Mechanize) a strict dependency for Daru.

I don't understand - maybe I'm missing out on the difference in terms `dependency` and `strict dependency` here? I mean, we would anyway have a dependency, for web scraping in `from_html`.

**Comment by zverok** [comment]
> I don't understand - maybe I'm missing out on the difference in terms dependency and strict dependency here? I mean, we would anyway have a dependency, for web scraping in from_html.

I mean, when you do `gem install daru` it should NOT install nokogiri, because it is large compiled gem not always easy to install (and not always necessary). Basically, there are two ways to achieve this goal:
1. As it is done with other optional libraries, do something like `require 'nokogiri'` inside `from_html`, catch `LoadError` and throw meaningful exception saying something like "Nokogiri is an optional dependency required to use `from_html`. Please install it manually".
2. Make separate `daru-importers` gem, including all the optional requirements.

I believe we could start with (1)

**Comment by athityakumar** [comment]
Sure. Currently, `Nokogiri` is already mentioned as a development dependency in the gemspec file [here](https://github.com/SciRuby/daru/blob/master/daru.gemspec#L77-L81) and in the `Gemfile.lock` file. So, we can just add the code for `from_html` with rescue statements to take care of `LoadError`.

BTW, is this `from_html` module to be added into `lib/daru/dataframe.rb` or at some other file?

**Comment by v0dro** [comment]
`strict dependency` = `runtime dependency`.

> BTW,  is this from_html module to be added into lib/daru/dataframe.rb or at some other file?

Why would it exist inside `dataframe.rb` when there is `io.rb` which contains all the `from_*` methods?

**Comment by athityakumar** [comment]
Thanks for the clarification, @v0dro . :smile: 

I'd like to work on this issue - I'll send a PR for the same by next week. (Have some exams coming up in the next 2 weeks)

**Comment by v0dro** [comment]
Works.

**Comment by athityakumar** [comment]
@v0dro - I think this can be closed. 😄
