### ISSUE TITLE
DataFrame#union method

### ISSUE THREAD

**Issue by genya0407** [SciRuby/daru#230]
When I concatenate two DataFrames, their index information disappears.

For example:

``` Ruby
df1 = Daru::DataFrame.new(
  {
    A:['A8', 'A9', 'A10', 'A11'],
    B:['B8', 'B9', 'B10', 'B11'],
    F:['F8', 'F9', 'F10', 'F11'],
    D:['D8', 'D9', 'D10', 'D11']
  },
  index: [10,11,12,13]
)
df2 = Daru::DataFrame.new(
  {
    A:['A8', 'A9', 'A10', 'A11'],
    B:['B8', 'B9', 'B10', 'B11'],
    F:['F8', 'F9', 'F10', 'F11'],
    D:['D8', 'D9', 'D10', 'D11']
  },
  index: [100, 101, 102, 103]
)

df1.concat(df2)
```

Above code results in the below DataFrame.
![untitled](https://cloud.githubusercontent.com/assets/3054386/17925633/a8d0859a-6a28-11e6-8e16-a40bcb73bee8.png)

**Comment by gnilrets** [comment]
That's by design.  Consider what would happen if both dataframes had the same index: you'd still want the two dataframes to be stacked.

If the indexes are important, consider converting them into a dataframe vector prior to concatenating.

That being said, perhaps we could write a `#union` method that would preserve the indexes and have some standard way of handling collisions.  For example, `df1.union(df2)`, rows in `df2` are preferred if they share an index with `df1`)

**Comment by v0dro** [comment]
Hmmm I agree with @gnilrets. @chart-linux could you change the name of your issue to reflect `DataFrame#union`? I'll mark it as enhancement once you do.

**Comment by Shekharrajak** [comment]
I think this issue must be closed, right ?

**Comment by v0dro** [comment]
Good find.
