### ISSUE TITLE
Design new daru release policy

### ISSUE THREAD

**Issue by v0dro** [SciRuby/daru#411]
A formal 'release policy' will concretely state the rules and regulations that our community will follow when releasing new versions of daru and its plugins. It will clearly state the version numbers that permit breaking changes and when will user code require an overhaul due to version updates.

**Comment by parthm** [comment]
Perhaps the release policy could also consider having some sort of a pre-release (RC?) for a week or two before the final. This would allow some of the active Daru users to try Daru on their apps and report any issues found before any final release. Case in point would be #386 (min/max break) which is serious enough to prevent an upgrade to 0.1.6. Eagerly waiting for 0.1.6.1 (0.1.7?) :yum:

**Comment by baarkerlounger** [comment]
I would suggest we adopt this as our release policy http://semver.org/ from now on for versioning (Next new feature would be 0.2.0, next bug fix would be 0.1.7, big code cleanup can become 1.0.0 if it's decided API has changed and/or is being considered the first really stable release). 

I would suggest we try to do releases more often also (happy to do this but think I would need elevated Repo permissions). Ideally at least patch release after every bug fix that's tagged as a major bug in the issue tracker. 

I like @parthm idea of a pre-release. I would suggest that not apply to patch releases (in order to get bug fixes out as quickly as possible) but possibly apply to all feature releases and certainly to all major (breaking change) releases.

If people are generally in agreement I can create some documentation for this. Otherwise let me know other ideas.

**Comment by zverok** [comment]
@baarkerlounger sounds pretty reasonable for me :+1:

**Comment by baarkerlounger** [comment]
Can this be closed given the above is merged?
